"""Shared data models used across detection, tracking, verification, and API layers."""

from __future__ import annotations

from datetime import datetime, timezone
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field


class ToolStatus(StrEnum):
    """Lifecycle states for accountable maintenance tools."""

    AVAILABLE = "available"
    IN_USE = "in_use"
    MISSING = "missing"
    RETURNED = "returned"


class AlertLevel(StrEnum):
    """Dashboard alert severity levels."""

    GREEN = "green"
    YELLOW = "yellow"
    RED = "red"


class BoundingBox(BaseModel):
    """Pixel-space bounding box."""

    x1: int
    y1: int
    x2: int
    y2: int

    def center(self) -> tuple[int, int]:
        """Return the center point of the bounding box."""

        return ((self.x1 + self.x2) // 2, (self.y1 + self.y2) // 2)


class Detection(BaseModel):
    """Single detector output before or after tracking assignment."""

    bbox: BoundingBox
    class_name: str
    confidence: float
    object_id: int | None = None
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class TrackedObject(Detection):
    """Detection with stable tracking metadata."""

    object_id: int
    disappeared_frames: int = 0


class ToolRecord(BaseModel):
    """Current accountability state for a detected tool."""

    unique_id: int
    tool_name: str
    entry_time: datetime
    exit_time: datetime | None = None
    current_position: tuple[int, int] | None = None
    movement_history: list[tuple[datetime, tuple[int, int]]] = Field(default_factory=list)
    status: ToolStatus = ToolStatus.IN_USE
    last_seen: datetime
    missing_since: datetime | None = None


class ChecklistItem(BaseModel):
    """Single maintenance checklist item."""

    id: int
    name: str
    required_tools: list[str] = Field(default_factory=list)
    completed: bool = False
    completed_at: datetime | None = None


class Alert(BaseModel):
    """Alert generated by the verification engine."""

    id: int | None = None
    level: AlertLevel
    message: str
    tool_id: int | None = None
    tool_name: str | None = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    resolved: bool = False
    metadata: dict[str, Any] = Field(default_factory=dict)
